#!/bin/bash
#SBATCH --job-name=NANOGrav_modif_final
#SBATCH --output=/fred/oz002/vdimarco/sky_scrambles/skies/outputs/NANOGrav_modif_final.out
#SBATCH --ntasks=1
#SBATCH --time=24:00:00
#SBATCH --tmp=8g
#SBATCH --mem-per-cpu=8g

unset PYTHONPATH
ml conda
conda activate ent15y             


python /fred/oz002/vdimarco/sky_scrambles/skies/NANOGrav_makeskyscrambles_val_mod_2.py
