#!/bin/bash
#SBATCH --job-name=PPTA_modif_final
#SBATCH --output=/fred/oz002/vdimarco/sky_scrambles/skies/outputs/PPTA_mod_final.out
#SBATCH --ntasks=1
#SBATCH --time=48:00:00
#SBATCH --tmp=8g
#SBATCH --mem-per-cpu=8g

unset PYTHONPATH
ml conda
conda activate ent15y             


python /fred/oz002/vdimarco/sky_scrambles/skies/PPTA_makeskyscrambles_val_mod.py
